### ISSUE TITLE
Convert bricks array to OHLC structure

### ISSUE THREAD

**Issue by novecento** [filipemarques87/fx-charts#1]
Hi, have you already worked about convert bricks array to OHLC structure?

**Comment by filipemarques87** [comment]
Hi @novecento, sorry for the late answer. No yet but I think it is a good idea. Maybe add an extra argument to indicate if the result returned should be a OHLC structure (can be active by default) or an array of prices (like it is happening right now).

**Comment by filipemarques87** [comment]
Renko charts return OHLC structure data instead returning the bottom of the renko candle
